#! /usr/bin/env bash
#
# run-example wrapper script.

# Script location
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Load global paths
source "${SCRIPT_DIR}/infrastructure/paths.sh"

# Activate the python venv
activate_venv

debug "Run: python3 \"${INFRASTRUCTURE_DIR}/run-example.py\" $@"
python3 "${INFRASTRUCTURE_DIR}/run-example.py" $@
