#! /bin/bash
#
# run-example wrapper script.

# Script location
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Load global paths
source "${SCRIPT_DIR}/infrastructure/paths.sh"

# Activate the virtual environment
source "${VPYTHON_ACTIVATE}"

python3 "${INFRASTRUCTURE_DIR}/run-example.py" $@
