libzmq:
    vcs: git
    url: https://github.com/zeromq/libzmq.git
    revision: "v4.3.1"
czmq:
    vcs: git
    url: https://github.com/zeromq/czmq.git
    revision: "v4.0.2"
cppzmq:
    vcs: git
    url: https://github.com/zeromq/cppzmq.git
    revision: "v4.2.2"
serial:
    vcs: git
    url: https://github.com/wjwwood/serial.git
    revision: "1.2.1"
sqlitecpp:
    vcs: git
    url: https://github.com/SRombauts/SQLiteCpp.git
    revision: "1.3.1"
zyre:
    vcs: git
    url: https://github.com/zeromq/zyre.git
    revision: "v2.0.0"
pugixml:
    vcs: git
    url: https://github.com/zeux/pugixml.git
    revision: "v1.2"
lmcpgen:
    vcs: git
    url: https://github.com/afrl-rq/LmcpGen.git
    revision: develop
openuxas:
    vcs: external
    url: .
    revision: None
amase:
    vcs: git
    url: https://github.com/afrl-rq/OpenAMASE.git
    revision: master
zeromqada:
    vcs: git
    url: https://github.com/persan/zeromq-Ada.git
    revision: master
