on:
    push:
        paths:
            - 'infrastructure/uxas/**'
    pull_request:
        paths:
            - 'infrastructure/uxas/**'

name: Build OpenAMASE
jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-18.04, ubuntu-20.04]
                component: [amase]
                qualifier: [scenario=release]
                python-version: [3.7, 3.8]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
              with:
                  path: OpenUxAS

            - name: Set up python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install infrastructure
              run: |
                  cd OpenUxAS
                  infrastructure/install -vv --no-gnat -y

            - name: Build OpenAMASE
              run: |
                  cd OpenUxAS
                  ./anod -v build ${{ matrix.component }} --qualifier=${{ matrix.qualifier}}
