on:
    push:
        paths:
            - 'infrastructure/uxas/**'
            - 'infrastructure/paths.sh'
            - 'anod'
            - 'src/ada/**'
            - 'tests/proof/**'
    pull_request:
        paths:
            - 'infrastructure/uxas/**'
            - 'infrastructure/paths.sh'
            - 'anod'
            - 'src/ada/**'
            - 'tests/proof/**'

name: "Build and Prove UxAS Ada Services"
jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-18.04, ubuntu-20.04]
                component: [uxas-ada]
                qualifier: [scenario=release]
                python-version: [3.7, 3.8]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
              with:
                  path: OpenUxAS

            - name: Set up python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install infrastructure
              run: |
                  cd OpenUxAS
                  infrastructure/install -vv --no-gnat -y

            - name: Install GNAT CE 2020
              if: ${{ matrix.component == 'uxas-ada' }}
              uses: ada-actions/toolchain@ce2020
              with:
                  distrib: community

            - name: Build OpenUxAS Ada
              run: |
                  cd OpenUxAS
                  ./anod -v build ${{ matrix.component }} --qualifier=${{ matrix.qualifier}}

            - name: Prove OpenUxAS Ada
              run: |
                  cd OpenUxAS/tests/proof
                  ./run-proofs -E --timeout=2400 --failure-exit-code=1
